version: 2

project_name: custom-ddns

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild

builds:
  - id: multi-platform
    builder: rust
    binary: custom-ddns
    targets:
      - x86_64-unknown-linux-gnu    # Linux x86_64
      - aarch64-unknown-linux-gnu   # Linux ARM64
      - x86_64-apple-darwin         # macOS Intel
      - aarch64-apple-darwin        # macOS Apple Silicon
    command: zigbuild
    flags:
      - --release



archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"



checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch

release:
  draft: false
  prerelease: auto 