version: 2

project_name: custom-ddns

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild

builds:
  - id: linux-builds
    builder: rust
    binary: custom-ddns
    targets:
      - x86_64-unknown-linux-gnu    # Linux x86_64
      - aarch64-unknown-linux-gnu   # Linux ARM64
    command: zigbuild
    flags:
      - --release



archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

dockers:
  - id: debian
    image_templates:
      - "ghcr.io/deimosfr/custom-ddns:{{ .Tag }}"
      - "ghcr.io/deimosfr/custom-ddns:latest"
      - "deimosfr/custom-ddns:{{ .Tag }}"
      - "deimosfr/custom-ddns:latest"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
    use: buildx

  - id: alpine
    image_templates:
      - "ghcr.io/deimosfr/custom-ddns:{{ .Tag }}-alpine"
      - "ghcr.io/deimosfr/custom-ddns:latest-alpine"
      - "deimosfr/custom-ddns:{{ .Tag }}-alpine"
      - "deimosfr/custom-ddns:latest-alpine"
    dockerfile: Dockerfile.alpine.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
    use: buildx

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch

release:
  draft: false
  prerelease: auto 