apiVersion: v1
kind: Secret
metadata:
  name: {{ include "custom-ddns.fullname" . }}-config
  labels:
    {{- include "custom-ddns.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: |
    {{- $config := dict }}
    {{- $_ := set $config "dns_records" .Values.config.dns_records }}
    {{- $config | toYaml | b64enc | nindent 4 }} 