name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Install rustfmt and clippy
        run: |
          rustup component add rustfmt
          rustup component add clippy
      
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
      
      - run: cargo test --verbose
      
      - run: cargo fmt --all -- --check
      
      - run: cargo clippy --all-targets --all-features -- -D warnings

  docker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-buildx-action@v3
      
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: false
      
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.alpine
          platforms: linux/amd64
          push: false 