name: Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  GITHUB_REPOSITORY: ${{ github.repository }}
  GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

jobs:
  goreleaser:
    permissions:
      contents: write
      packages: write
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0

      - name: Install cargo-zigbuild and targets
        run: |
          cargo install --locked cargo-zigbuild
          rustup target add x86_64-unknown-linux-gnu
          rustup target add aarch64-unknown-linux-gnu
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin



      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 